### ISSUE TITLE
Quality info on barcodes and UMI sequences

### ISSUE THREAD

**Issue by davidecrs** [cgplab/ddSeeker#3]
Hi,

I'm using your software to analyze a BioRad dataset and I'd like to get the quality line of the barcodes and UMI sequences recognized by the software. 
Is it possible to get these information, for example as additional tags in the uBAM file ?

Best regards,
Davide

**Comment by romagnolid** [comment]
Hi @davidecrs, glad to hear you're using our software.
I'll work on that and make a new release in the next days.

**Comment by davidecrs** [comment]
Thanks a lot !

**Comment by romagnolid** [comment]
@davidecrs welcome, let me know if this solution works well for you

**Comment by davidecrs** [comment]
Hi @romagnolid,

First of all, thanks for your time. I ran ddSeeker with the new features of umi and barcodes quality, but sometimes it produces a row, in the output bam file, with a mismatch in the string length between barcode (tag XB) and quality barcode (tag BQ).
This is an example row: 
 
`NB501072:248:HNKTFBGXC:1:11101:18387:1061:ACCGATGTAGCCATCGCATTGCGAGAGCCTACCTCTGAGCTGAAGCCAGAACGATTCTGAGGAACTTT	4	*	0	0	*	*	0	75	GCCATATATGTAATATACACAAACTCAATTAGCATTGTAATGGCCAAATGCATTCCCCCATGCTTTTCTGTTTTC	AAAAAEA/E/EEEE<EEEEEA/AEEEEA/EE/EEAE/E/6<A<AAE</EEEA/EE/6/<A/A<A//<EEAA/A//	XB:Z:CCGATGGAGGCCGCCAGA	XU:Z:ATTCTGAG	UQ:Z:EEEEEEEE	BQ:Z:AAAAEEEEEEEEEEEEEEE`

More specifically:
```
XB:Z:CCGATGGAGGCCGCCAGA    (length: 18)
BQ:Z:AAAAEEEEEEEEEEEEEEE    (length: 19)
```

**Comment by romagnolid** [comment]
Hi @davidecrs,
I noticed the issue and added a note in the README but I forgot to update the github repository, my mistake.

Anyway, the problem is:
the cell barcode is composed by three shorter blocks and if any of the block is affected by and indel event it may be difficult to determine which base was inserted/deleted (although each block is fixed by comparing it to a list of available blocks). Therefore, the quality string of the cell barcode may differ in length with respect to the proper cell barcode by one base.

`E.g. correct block: TTTGGG; observed block: TTTGGGG`
In this case it's impossible to know which "G" is an insertion and to retrieve the corresponding quality.
In other situations (such as an insertion of "A" in the previous block) it would be easier but I'd have to rewrite a good portion of the code.

In brief, it's impossible to know the quality of each base but it gives a general view of the quality of the barcode.

Hope it helps
