### ISSUE TITLE
Analysis from fastq.gz to counts table/Seurat

### ISSUE THREAD

**Issue by tstokowy** [cgplab/ddSeeker#5]
Dear ddSeeker authors,
Could you recommend a pipeline which goes from fastq.gz files to Seurat supported input? I would like it to work well with human and mouse reference genomes. I did not manage to find suitable script that would support ddSeq technology.

Kind regards,
Tomasz Stokowy

**Comment by romagnolid** [comment]
Hello @tstokowy, you can use our script `ddSeeker_dropSeq_tools.sh`. It requires a bit of tweaking but in the end you will get a matrix of counts (cells X transcripts). Check the usage of the script (just launch it without options).
You need to download Drop-seq  and STAR and all the data used by these tools.
http://mccarrolllab.org/dropseq/
https://github.com/alexdobin/STAR
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1629193

Also be sure to use the legacy version (1.13) of Drop-Seq because version 2.X doesn't work with our pipeline yet.
If the pipeline works correctly then launch following command to obtain the matrix
```
./DigitalExpression 
INPUT=merged.bam
OUTPUT=sample.dge.txt.gz
SUMMARY=sample.dge.summary.txt
CELL_BARCODE_TAG=XC
MOLECULAR_BARCODE_TAG=XM
NUM_CORE_BARCODES=2000  
(set this number to the predicted number of single cells retrieved by the experiment skip it completely)
```

**Comment by tstokowy** [comment]
Thank you, this is very helpful. Once I read documentation of ddSeeker_dropSeq_tools.sh things became clear.
